### ISSUE TITLE
【たっけ】　README.mdの記述

### ISSUE THREAD

**Issue by Kazzle619** [DMM-WEBCAMP-Avengers/nagano_cake#171]
お願いします！

**Comment by takenomori** [comment]
わかりました

**Comment by tsakszk** [comment]
どちらかが記述でいいですか？
僕はでひとまず今出来上がっているコードを見て勉強したいです！

**Comment by takenomori** [comment]
じゃあ、自分が今日、明日で書いておきます

**Comment by tsakszk** [comment]
ありがとうございます。
「READMEファイルについて」というDMMのスライドがあったかと思いましたので、念のため情報共有しておきます。
よろしくお願いします。
