### ISSUE TITLE
【全体⑤】　各コントローラーの必要なアクションへbefore_actionを追加

### ISSUE THREAD

**Issue by Kazzle619** [DMM-WEBCAMP-Avengers/nagano_cake#59]
⚠実装の邪魔になるので全てのページが完成してから実装すべき

ログインしたときのみ見れるページがあるはずなので、それらに
authenticate_user!
authenticate_admin_user!
をつける。

**Comment by tsakszk** [comment]
EC(会員)サイト
商品詳細ページからカートに追加する処理で、public/cart_productsコントローラーにauthenticate_user!入れてます。
フレンドリーフォワーディングがうまくいかなかったのと、シンプルに習ったものを入れた感じです。
必要であればフレンドリーフォワーディングを実装いただいた方がいいかもしれないです。
