### ISSUE TITLE
【とし】 renderするとビューが崩れる問題の解消　参照の通りで解決します！！

### ISSUE THREAD

**Issue by Kazzle619** [DMM-WEBCAMP-Avengers/nagano_cake#90]
formでsaveやcreateの失敗後にrenderをするとビューが崩れたページを表示してしまう。

**Comment by tsakszk** [comment]
https://qiita.com/takuya_33/items/e0c67feca20b67a2fe44
参照

**Comment by Kazzle619** [comment]
CSSいじればOK
